<a href="https://colab.research.google.com/github/esharma3/data_structures/blob/main/data_structures_sort_algos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **BUBBLE Sort** O(n**2)

Repeatedly steps through the list, compares the two adjacent elements and swaps them until the list is sorted.

In [1]:
import pandas as pd
import numpy as np

random.randint(low, high=None, size=None, dtype=int)

Return random integers from low (inclusive) to high (exclusive).

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).

In [2]:
random_arr = np.random.randint(1,10,5)
random_arr

array([4, 7, 5, 8, 5])

In [3]:
def bubble_sort(arr):
    n = len(arr)
    for i in range(n):    # note the two for loops; with every full iteration of a single i, we push the largest element at the end
        for j in range(n-i-1):     # for each value of i, we iterate through the whole list n-i-1 times; if i=1, then j=5-1-1=3 and push the largest element at the end & that's why we can keep skipping the last element in this inner for loop by doing j=n-i-1
            print("i: ", i)
            print("j: ", j)
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    return arr

In [4]:
%%time
print("original arr: ", random_arr)
sorted_arr = bubble_sort(random_arr)
sorted_arr

original arr:  [4 7 5 8 5]
i:  0
j:  0
i:  0
j:  1
i:  0
j:  2
i:  0
j:  3
i:  1
j:  0
i:  1
j:  1
i:  1
j:  2
i:  2
j:  0
i:  2
j:  1
i:  3
j:  0
CPU times: user 5.03 ms, sys: 1.01 ms, total: 6.04 ms
Wall time: 6.33 ms


array([4, 5, 5, 7, 8])

In [5]:
# same code as in the above cell but without print statement to track actual time
def bubble_sort(arr):
    n = len(arr)
    for i in range(n):    # note the two for loops; with every full iteration of a single i, we push the largest element at the end
        for j in range(n-i-1):     # for each value of i, we iterate through the whole list n-i-1 times; if i=1, then j=5-1-1=3 and push the largest element at the end & that's why we can keep skipping the last element in this inner for loop by doing j=n-i-1
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    return arr

In [6]:
# IMP - I cannot reuse the random input array created initially because it got sorted inplace after the first sorting was run on it; so creating a new one before each sort
random_arr = np.random.randint(1,10,5)
random_arr

array([4, 3, 4, 8, 6])

In [7]:
%%time
print("original arr: ", random_arr)
sorted_arr = bubble_sort(random_arr)
sorted_arr

original arr:  [4 3 4 8 6]
CPU times: user 204 µs, sys: 40 µs, total: 244 µs
Wall time: 262 µs


array([3, 4, 4, 6, 8])

# **Selection Sort** O(n**2)

Repeatedly finds the minimum element from the unsorted part of the list and places that at the beginning of the list.

** select the minimum element and move it at the beginning of the list.

In [8]:
def selection_sort(arr):
    n = len(arr)
    for i in range(n):    # note the two for loops
        min_index = i
        for j in range(i+1, n):   # i+1 because i will have the minimum element, so we need to start the comparion from i+1 element always  
            if arr[j] < arr[min_index]:
                min_index = j
        arr[i], arr[min_index] = arr[min_index], arr[i]   # moves the element at the new min_index(=j) to the i-th location which is the first position of the unsorted part of list & moves the initial i-th element to the previous min_index position
    return arr

In [9]:
# IMP - I cannot reuse the random input array created initially because it got sorted inplace after the first sorting was run on it; so creating a new one before each sort
random_arr = np.random.randint(1,10,5)
random_arr

array([9, 2, 6, 2, 2])

In [10]:
%%time
print("original arr: ", random_arr)
selection_sorted_arr = selection_sort(random_arr)
selection_sorted_arr

original arr:  [9 2 6 2 2]
CPU times: user 294 µs, sys: 1.04 ms, total: 1.34 ms
Wall time: 1.34 ms


array([2, 2, 2, 6, 9])

# **Insertion Sort** O(n**2)

It builds the final sorted list one element at a time by inserting each unsorted element into its correct position in the sorted part of the list.

In [11]:
def insertion_sort(arr):
    n = len(arr)
    for i in range(1,n):
        key = arr[i]
        print("key - first element of unsorted part of list: ", key)

        j = i-1
        print("j: ", j)
        print("arr[j] - last element of sorted part of list: ", arr[j])
        while j >= 0 and arr[j] > key:
            arr[j+1] = arr[j]
            j = j-1
        arr[j+1] = key
        print("arr[j+1]: ", arr[j+1])
    return arr

In [12]:
# IMP - I cannot reuse the random input array created initially because it got sorted inplace after the first sorting was run on it; so creating a new one before each sort
random_arr = np.random.randint(1,10,5)
random_arr

array([2, 9, 3, 3, 7])

In [13]:
print("original arr: ", random_arr)
insertion_sorted_arr = insertion_sort(random_arr)
print("sorted arr: ", insertion_sorted_arr)

original arr:  [2 9 3 3 7]
key - first element of unsorted part of list:  9
j:  0
arr[j] - last element of sorted part of list:  2
arr[j+1]:  9
key - first element of unsorted part of list:  3
j:  1
arr[j] - last element of sorted part of list:  9
arr[j+1]:  3
key - first element of unsorted part of list:  3
j:  2
arr[j] - last element of sorted part of list:  9
arr[j+1]:  3
key - first element of unsorted part of list:  7
j:  3
arr[j] - last element of sorted part of list:  9
arr[j+1]:  7
sorted arr:  [2 3 3 7 9]


# **Merge Sort** O(n log n)

In [14]:
def merge_sort(arr):
    # arr = arr1.copy()
    print("splitting array: ", arr)
    if len(arr) > 1:  
        mid = len(arr) // 2    # floor division    
        left = arr[:mid]
        right = arr[mid:]
        # print("left: ", left)
        # print("right: ", right)
        merge_sort(left)
        merge_sort(right)

        i = j = k = 0   # index for left, right and resultant list respectively

        while i < len(left) and j < len(right):  # sorting and merging is happening together here
            if left[i] <= right[j]:
                arr[k] = left[i]
                i = i + 1
            else:
                arr[k] = right[j]
                j = j + 1
            k = k + 1

        while i < len(left):
            arr[k] = left[i]
            i = i + 1
            k = k + 1

        while j < len(right):
            arr[k] = right[j]
            j = j + 1
            k = k + 1

    print("merging: ", arr)


In [15]:
merge_arr = np.random.randint(1, 10, 8)
merge_arr

array([5, 7, 2, 8, 2, 9, 3, 5])

In [16]:
arr = [4, 2, 4, 1, 8, 6, 8, 9]
nlist = [14,46,43,27,57,41,45,21,70]
merge_sort(nlist)

splitting array:  [14, 46, 43, 27, 57, 41, 45, 21, 70]
splitting array:  [14, 46, 43, 27]
splitting array:  [14, 46]
splitting array:  [14]
merging:  [14]
splitting array:  [46]
merging:  [46]
merging:  [14, 46]
splitting array:  [43, 27]
splitting array:  [43]
merging:  [43]
splitting array:  [27]
merging:  [27]
merging:  [27, 43]
merging:  [14, 27, 43, 46]
splitting array:  [57, 41, 45, 21, 70]
splitting array:  [57, 41]
splitting array:  [57]
merging:  [57]
splitting array:  [41]
merging:  [41]
merging:  [41, 57]
splitting array:  [45, 21, 70]
splitting array:  [45]
merging:  [45]
splitting array:  [21, 70]
splitting array:  [21]
merging:  [21]
splitting array:  [70]
merging:  [70]
merging:  [21, 70]
merging:  [21, 45, 70]
merging:  [21, 41, 45, 57, 70]
merging:  [14, 21, 27, 41, 43, 45, 46, 57, 70]


# **Quick Sort** O(n log n)

1. select a pivot element - randomly or first element or last element
2. partition the list around the pivot, all smaller elements on the left of the pivot and all larger elements on the right of the pivot
3. recursively apply quick sort to the sub lists until the sub lists have a length of 1 or 0
4. combine the sorted sub lists: left + pivot + right

In [17]:
arr_quick = np.random.randint(1,10,8)
arr_quick

array([8, 2, 8, 4, 8, 8, 9, 9])

In [36]:
def quick_sort(lst):

    if len(lst) <= 1:
        return lst

    pivot = lst[-1]
    print("pivot", pivot)
    n = len(lst)
    i = 0

    for j in range(n-1):    # n-1 because we want to exclude the pivot at the last position lst[-1]
        print("i ", i)
        print("lst[i]", lst[i])
        print("j ", j)
        print("lst[j]", lst[j])
        if lst[j] < pivot:
            lst[i], lst[j] = lst[j], lst[i]
            i = i + 1

    lst[i], lst[-1] = lst[-1], lst[i]

    left = quick_sort(lst[:i])
    # print("left", left)

    right = quick_sort(lst[i+1:])
    # print("right", right)

    return left + [lst[i]] + right

In [37]:
lst = [13,2,5,1,55,0, 15]
# quick_sort(arr_quick)   # this returns empty list # this code is not working for arrays. It is onky working for lists.

In [38]:
print("original list ", lst)
quick_sort(lst)

original list  [13, 2, 5, 1, 55, 0, 15]
pivot 15
i  0
lst[i] 13
j  0
lst[j] 13
i  1
lst[i] 2
j  1
lst[j] 2
i  2
lst[i] 5
j  2
lst[j] 5
i  3
lst[i] 1
j  3
lst[j] 1
i  4
lst[i] 55
j  4
lst[j] 55
i  4
lst[i] 55
j  5
lst[j] 0
pivot 0
i  0
lst[i] 13
j  0
lst[j] 13
i  0
lst[i] 13
j  1
lst[j] 2
i  0
lst[i] 13
j  2
lst[j] 5
i  0
lst[i] 13
j  3
lst[j] 1
pivot 13
i  0
lst[i] 2
j  0
lst[j] 2
i  1
lst[i] 5
j  1
lst[j] 5
i  2
lst[i] 1
j  2
lst[j] 1
pivot 1
i  0
lst[i] 2
j  0
lst[j] 2
i  0
lst[i] 2
j  1
lst[j] 5
pivot 2
i  0
lst[i] 5
j  0
lst[j] 5


[0, 1, 2, 5, 13, 15, 55]